# Generated by Django 4.1.5 on 2023-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log_in_registtration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=30)),
                ('password', models.TextField(max_length=20)),
                ('account_type', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
