# Generated by Django 4.1.5 on 2023-03-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_in_registtration',
            name='pub_date',
        ),
    ]
