# Generated by Django 4.1.5 on 2023-03-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_log_in_registtration_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='thumnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.TextField(max_length=30)),
                ('Chapter_name', models.TextField(max_length=30)),
                ('Topic_name', models.TextField(max_length=30)),
                ('Thumnail_image', models.ImageField(upload_to='Registration/thumnail')),
                ('Short_Desc', models.TextField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
