# Generated by Django 4.1.5 on 2023-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_name', models.TextField(max_length=30)),
                ('Topic_name', models.TextField(max_length=30)),
                ('Leactur_title', models.TextField(max_length=30)),
                ('Desc_leactur', models.TextField(max_length=30)),
                ('leactur', models.FileField(upload_to='Registration/video')),
            ],
        ),
    ]
