# Generated by Django 4.1.5 on 2023-03-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='Chapter_name',
            new_name='Chapter_name_playlist',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='Topic_name',
            new_name='Topic_name_playlist',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='leactur',
            new_name='Upload_leactur',
        ),
    ]
