# Generated by Django 4.1.5 on 2023-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_rename_chapter_name_playlist_chapter_name_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quize_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quize_name', models.CharField(max_length=30)),
                ('chaptr_name', models.CharField(max_length=30)),
                ('topic_name', models.CharField(max_length=30)),
                ('thumnail', models.ImageField(upload_to='Registration/Quize/thumnail')),
                ('marks_per_que', models.TextField(max_length=2)),
                ('descreption', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='thumnail',
            name='Thumnail_image',
            field=models.ImageField(upload_to='Registration/playlist/thumnail'),
        ),
    ]
