# Generated by Django 4.1.5 on 2023-04-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_quize_name_alter_thumnail_thumnail_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quize_name',
            new_name='Quize_thumnail',
        ),
    ]
