# Generated by Django 4.1.5 on 2023-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_rename_quize_name_quize_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quize_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quize_name', models.CharField(max_length=30)),
                ('chaptr_name', models.CharField(max_length=30)),
                ('topic_name', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=500)),
                ('correct_option', models.CharField(max_length=500)),
                ('option_one', models.CharField(max_length=200)),
                ('option_two', models.CharField(max_length=200)),
                ('option_three', models.CharField(max_length=200)),
            ],
        ),
    ]
