# Generated by Django 4.1.5 on 2023-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_quize_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize_questions',
            name='correct_option',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
