# Generated by Django 4.1.5 on 2023-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0012_alter_quize_questions_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize_questions',
            name='correct_option',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
