# Generated by Django 4.1.5 on 2023-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_alter_quize_questions_correct_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
