# Generated by Django 4.1.5 on 2023-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_notic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notic',
            name='Heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
