# Generated by Django 4.1.5 on 2023-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_alter_notic_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notic',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
